sudo: required
language: generic

services:
    - docker

before_install:
    - docker build -t alexf/frontend -f Dockerfile.dev .
    
script:
    - docker run -e CI=true alexf/frontend npm run test -- --watchAll=false